language: php

matrix:
  include:
    - php: 5.4
    - php: 5.5
      env: COVERALLS=yes
    - php: 5.6
    - php: 7.0
    - php: hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit --coverage-text
